import type { Category } from "@/lib/categories";

export type ProjectThumbnails = {
  desktop: string;
  tablet?: string;
  mobile?: string;
};

export type Project = {
  slug: string;
  title: string;
  url: string;
  category: Category;
  tags: string[];
  featured: boolean;
  year: number;
  description: string;
  goal: string;
  solution: string;
  highlights: string[];
  thumbnails: ProjectThumbnails;
  industryNotes: string;
};

const commonTags = ["Next.js", "React", "Tailwind", "Responsive", "SEO", "UI/UX", "Vercel"];

const t = (slug: string): ProjectThumbnails => ({
  desktop: `/thumbnails/${slug}-desktop.jpg`,
  tablet: `/thumbnails/${slug}-tablet.jpg`,
  mobile: `/thumbnails/${slug}-mobile.jpg`,
});

export const projects: Project[] = [
  {
    slug: "delicacies-spot",
    title: "Delicacies Spot",
    url: "https://delicacies-spot.vercel.app/",
    category: "Restaurants & Food",
    tags: commonTags,
    featured: true,
    year: 2026,
    description: "Premium restaurant website engineered to lift reservations, menu exploration, and direct customer inquiries.",
    goal: "Improve first impression and guide visitors toward booking or inquiry actions quickly.",
    solution:
      "Delivered a mobile-first restaurant experience with clear menu pathways, visual storytelling, and conversion-oriented CTA placement.",
    highlights: ["Fast-loading hero and menu sections", "Inquiry-first layout", "Clear contact flow", "SEO-ready metadata structure"],
    thumbnails: t("delicacies-spot"),
    industryNotes: "Food customers decide quickly; clarity and appetite-focused visuals drive conversion.",
  },
  {
    slug: "evecs-seven",
    title: "EVECs Seven",
    url: "https://evecs-seven.vercel.app/",
    category: "Systems / Other",
    tags: commonTags,
    featured: false,
    year: 2026,
    description: "Corporate web presence structured to clarify services, reinforce credibility, and support business inquiries.",
    goal: "Present core services in a structured, professional interface for broad business audiences.",
    solution:
      "Built a scalable interface pattern with responsive sections, concise service copy, and polished hierarchy to support credibility.",
    highlights: ["Professional visual hierarchy", "Responsive layout system", "Scalable section architecture", "Conversion-focused contact blocks"],
    thumbnails: t("evecs-seven"),
    industryNotes: "Corporate users value credibility and navigation simplicity over novelty.",
  },
  {
    slug: "resort-mu",
    title: "Resort Mu",
    url: "https://resort-mu.vercel.app/",
    category: "Resorts & Hotels",
    tags: commonTags,
    featured: false,
    year: 2026,
    description: "Resort marketing website built to strengthen destination appeal and increase direct booking intent.",
    goal: "Showcase destination value and guide users to reservation actions with minimal friction.",
    solution: "Designed immersive resort sections, booking-oriented UX paths, and mobile-optimized presentation for travel audiences.",
    highlights: ["Destination-led storytelling", "Booking CTA emphasis", "Mobile travel usability", "Performance-focused media handling"],
    thumbnails: t("resort-mu"),
    industryNotes: "Travel conversion improves when visuals and booking signals are tightly integrated.",
  },
  {
    slug: "haven-dine",
    title: "Haven Dine",
    url: "https://haven-dine.vercel.app/",
    category: "Restaurants & Food",
    tags: commonTags,
    featured: true,
    year: 2026,
    description: "Fine-dining website built to elevate brand perception and increase reservation conversion.",
    goal: "Create an upscale digital experience that matches premium in-person dining expectations.",
    solution:
      "Shipped a cinematic dining layout with high-contrast typography, smooth interactions, and conversion-ready reservation pathways.",
    highlights: ["Premium brand presentation", "Reservation-first UX", "Fluid responsive behavior", "Clean information hierarchy"],
    thumbnails: t("haven-dine"),
    industryNotes: "Luxury hospitality demands high visual quality and deliberate interaction pacing.",
  },
  {
    slug: "yum-yard",
    title: "Yum Yard",
    url: "https://yum-yard-kappa.vercel.app/",
    category: "Restaurants & Food",
    tags: commonTags,
    featured: true,
    year: 2026,
    description: "Modern restaurant brand website built for stronger menu engagement and inquiry conversion.",
    goal: "Increase menu exploration and action-taking on mobile-first audiences.",
    solution: "Implemented appetite-driven visuals, clear service content, and conversion prompts aligned with browsing behavior.",
    highlights: ["Brand-consistent visuals", "Mobile-first menu UX", "SEO-ready pages", "Inquiry-focused CTA structure"],
    thumbnails: t("yum-yard"),
    industryNotes: "Food branding works best when visuals, speed, and CTA clarity are aligned.",
  },
  {
    slug: "oasis-twist-dine",
    title: "Oasis Twist Dine",
    url: "https://oasis-twist-dine.vercel.app/",
    category: "Restaurants & Food",
    tags: commonTags,
    featured: false,
    year: 2026,
    description: "Restaurant website crafted to improve brand recall, menu discovery, and inquiry flow.",
    goal: "Turn first-time visits into meaningful engagement and booking interest.",
    solution: "Designed an interaction-rich but lightweight website with clear user pathways from browsing to contact.",
    highlights: ["Conversion-friendly page pacing", "Consistent brand sections", "Mobile readability", "Smooth micro-interactions"],
    thumbnails: t("oasis-twist-dine"),
    industryNotes: "Restaurant sites perform better when menu, atmosphere, and action paths are immediate.",
  },
  {
    slug: "stop-eat-go",
    title: "Stop Eat Go",
    url: "https://stop-eat-go.vercel.app/",
    category: "Restaurants & Food",
    tags: commonTags,
    featured: false,
    year: 2026,
    description: "Fast-loading food website designed for quick menu access and faster direct customer action.",
    goal: "Reduce friction from landing to menu/contact action.",
    solution: "Built a lightweight, conversion-ready layout with high-speed rendering and straightforward calls-to-action.",
    highlights: ["Fast initial load", "Clear menu path", "Simple CTA hierarchy", "Mobile-first responsiveness"],
    thumbnails: t("stop-eat-go"),
    industryNotes: "Quick-service audiences reward speed and direct action routes.",
  },
  {
    slug: "velocity-builder",
    title: "Velocity Builder Gym",
    url: "https://velocity-builder.vercel.app/",
    category: "Fitness & Gym",
    tags: commonTags,
    featured: true,
    year: 2026,
    description: "Fitness website positioned to convert visitor interest into membership and trial-signup action.",
    goal: "Motivate visitors to take trial and membership actions with trust-driven content.",
    solution: "Combined bold fitness visuals, confidence-building messaging, and strong conversion entry points for mobile users.",
    highlights: ["Trust-led hero messaging", "Trial signup-focused CTA flow", "Strong mobile presentation", "SEO-ready page structure"],
    thumbnails: t("velocity-builder"),
    industryNotes: "Fitness users convert through aspiration + clear signup pathways.",
  },
  {
    slug: "paws-claws-veterinary-clinic",
    title: "Paws & Claws Veterinary Clinic",
    url: "https://paws-claws-veterinary-clinic.vercel.app/",
    category: "Pets & Veterinary",
    tags: commonTags,
    featured: false,
    year: 2026,
    description: "Veterinary clinic website designed to strengthen owner trust and increase appointment inquiries.",
    goal: "Communicate care quality and make pet health services easy to access.",
    solution: "Built a compassionate, easy-to-navigate clinic experience with clear services, emergency cues, and contact conversion points.",
    highlights: ["Trust-first interface", "Service clarity", "Responsive contact flow", "Accessible typography and contrast"],
    thumbnails: t("paws-claws-veterinary-clinic"),
    industryNotes: "Pet care websites need emotional trust and immediate service clarity.",
  },
  {
    slug: "pearlsmile-dental-clinic",
    title: "PearlSmile Dental Clinic",
    url: "https://pearlsmile-dental-clinic.vercel.app/",
    category: "Healthcare & Clinics",
    tags: commonTags,
    featured: false,
    year: 2026,
    description: "Dental clinic website optimized for consultation requests and patient confidence.",
    goal: "Help new patients understand services and quickly request appointments.",
    solution: "Delivered a clean healthcare layout with trust signals, service highlights, and conversion-focused inquiry placement.",
    highlights: ["Healthcare-ready UI clarity", "Consultation CTA strategy", "Mobile appointment usability", "SEO-focused content structure"],
    thumbnails: t("pearlsmile-dental-clinic"),
    industryNotes: "Healthcare conversion depends on trust, clarity, and frictionless contact.",
  },
  {
    slug: "primecare-medical-clinic",
    title: "PrimeCare Medical Clinic",
    url: "https://primecare-medical-clinic.vercel.app/",
    category: "Healthcare & Clinics",
    tags: commonTags,
    featured: true,
    year: 2026,
    description: "Medical clinic website structured to guide patients clearly and increase qualified inquiries.",
    goal: "Improve patient confidence and increase medical inquiry submissions.",
    solution: "Built a professional clinic experience with structured service pathways, doctor-ready sections, and conversion-focused actions.",
    highlights: ["Professional medical branding", "Action-oriented page structure", "Responsive across devices", "Performance and SEO ready"],
    thumbnails: t("primecare-medical-clinic"),
    industryNotes: "Medical websites must prioritize trust cues and clear next-step guidance.",
  },
  {
    slug: "savoryspot",
    title: "SavorySpot",
    url: "https://savoryspot-orpin.vercel.app/",
    category: "Restaurants & Food",
    tags: commonTags,
    featured: false,
    year: 2026,
    description: "Restaurant website structured around a cleaner customer journey from first visit to booking action.",
    goal: "Drive visitors from exploration to booking and inquiry in fewer steps.",
    solution: "Implemented menu-centric UX, mobile-first section flow, and conversion placements tuned for food browsing behavior.",
    highlights: ["Menu-forward architecture", "High mobile usability", "Conversion-driven CTAs", "SEO-friendly structure"],
    thumbnails: t("savoryspot"),
    industryNotes: "Restaurant funnels should make decisions easy in under a minute.",
  },
  {
    slug: "auto-spot",
    title: "Auto Spot",
    url: "https://auto-spot-smoky.vercel.app/",
    category: "Automotive",
    tags: commonTags,
    featured: false,
    year: 2026,
    description: "Automotive services website designed to build trust and convert service inquiries more effectively.",
    goal: "Showcase automotive services clearly while maximizing quote and contact requests.",
    solution: "Built a structured automotive interface with strong service hierarchy and quick-action inquiry options.",
    highlights: ["Service-centric layout", "Quote-ready callouts", "Responsive performance", "Business-oriented contact flow"],
    thumbnails: t("auto-spot"),
    industryNotes: "Automotive users convert on trust, speed, and service clarity.",
  },
  {
    slug: "azure-waves-resort",
    title: "Azure Waves Resort",
    url: "https://azure-waves-resort.vercel.app/",
    category: "Resorts & Hotels",
    tags: commonTags,
    featured: true,
    year: 2026,
    description: "Premium resort website balancing destination storytelling with clearer booking conversion cues.",
    goal: "Increase direct booking intent and improve perceived resort value.",
    solution: "Designed a visual-first resort flow with strategically placed booking prompts and responsive experience quality.",
    highlights: ["Cinematic resort presentation", "Booking-focused structure", "Smooth responsive behavior", "SEO and speed optimized"],
    thumbnails: t("azure-waves-resort"),
    industryNotes: "Resort experiences should inspire quickly and convert before users leave the page.",
  },
  {
    slug: "hotel-seven-blue",
    title: "Hotel Seven Blue",
    url: "https://hotel-seven-blue.vercel.app/",
    category: "Resorts & Hotels",
    tags: commonTags,
    featured: false,
    year: 2026,
    description: "Hotel website engineered to improve room discovery and increase reservation inquiries.",
    goal: "Simplify traveler navigation from homepage to room inquiry.",
    solution: "Implemented a structured hospitality interface with clear room highlights, trust cues, and action-driven CTAs.",
    highlights: ["Hospitality-first page hierarchy", "Room discovery clarity", "Mobile booking support", "Performance-focused build"],
    thumbnails: t("hotel-seven-blue"),
    industryNotes: "Hotel conversions increase when room value and action paths are obvious.",
  },
  {
    slug: "apex-real-estate",
    title: "Apex Real Estate",
    url: "https://apex-real-estate-nu.vercel.app/",
    category: "Real Estate",
    tags: commonTags,
    featured: true,
    year: 2026,
    description: "Real estate website built to turn listing interest into qualified buyer and seller inquiries.",
    goal: "Improve listing exploration and increase serious buyer/seller leads.",
    solution: "Delivered an agent-friendly real estate UX with listing clarity, trust sections, and conversion-led call-to-actions.",
    highlights: ["Listing-focused UX", "Lead capture optimization", "Mobile browsing quality", "SEO-ready structure"],
    thumbnails: t("apex-real-estate"),
    industryNotes: "Property audiences need trust, clarity, and immediate next-step options.",
  },
  {
    slug: "affiliate-three",
    title: "Affiliate Three",
    url: "https://affiliate-three-kappa.vercel.app/",
    category: "Affiliate / Marketing",
    tags: commonTags,
    featured: false,
    year: 2026,
    description: "Affiliate marketing website optimized for clearer offers, stronger click-through, and campaign conversion.",
    goal: "Increase campaign action rates through clear offer communication.",
    solution: "Built a performance-conscious marketing interface with focused copy hierarchy and conversion pathways.",
    highlights: ["Offer-centric structure", "Fast campaign pages", "Responsive CTA sections", "SEO-supportive layout"],
    thumbnails: t("affiliate-three"),
    industryNotes: "Affiliate pages perform best when value proposition is immediate and uncluttered.",
  },
  {
    slug: "salon-iota",
    title: "Salon Iota",
    url: "https://salon-iota-ochre.vercel.app/",
    category: "Beauty & Wellness",
    tags: commonTags,
    featured: false,
    year: 2026,
    description: "Salon website built to support appointment inquiries with a more premium brand presentation.",
    goal: "Present services elegantly while maximizing booking intent.",
    solution: "Created a beauty-focused web experience with polished sections, service highlights, and conversion-first CTAs.",
    highlights: ["Elegant salon visual style", "Appointment-oriented flow", "Mobile-friendly UX", "Fast and SEO-aware"],
    thumbnails: t("salon-iota"),
    industryNotes: "Wellness users respond to premium aesthetics backed by clear service details.",
  },
  {
    slug: "roadgo-rental",
    title: "RoadGo Rental",
    url: "https://roadgorental.vercel.app/",
    category: "Rentals",
    tags: commonTags,
    featured: false,
    year: 2026,
    description: "Rental business website designed to improve fleet visibility and speed up booking requests.",
    goal: "Reduce friction from vehicle browsing to reservation inquiry.",
    solution: "Implemented a rental-focused interface with clear fleet sections, trust indicators, and quick conversion controls.",
    highlights: ["Fleet-first browsing UX", "Lead-ready inquiry blocks", "Responsive performance", "Strong call-to-action hierarchy"],
    thumbnails: t("roadgo-rental"),
    industryNotes: "Rental customers prioritize speed, pricing clarity, and immediate contact options.",
  },
  {
    slug: "feel-at-home-spa",
    title: "Feel At Home Spa",
    url: "https://feelathomespa.vercel.app/",
    category: "Beauty & Wellness",
    tags: commonTags,
    featured: false,
    year: 2026,
    description: "Spa website crafted to support relaxation branding, trust, and stronger booking intent.",
    goal: "Increase treatment inquiry rate while preserving a premium wellness feel.",
    solution: "Developed a calm, conversion-focused spa layout with clear treatment presentation and mobile-first usability.",
    highlights: ["Wellness-focused visual rhythm", "Service clarity", "Mobile conversion UX", "SEO and performance baseline"],
    thumbnails: t("feel-at-home-spa"),
    industryNotes: "Spa conversion depends on mood consistency + easy appointment pathways.",
  },
  {
    slug: "provider-steel",
    title: "Provider Steel",
    url: "https://provider-steel-smoky.vercel.app/",
    category: "Agency / Corporate",
    tags: commonTags,
    featured: false,
    year: 2026,
    description: "Corporate services website built to communicate credibility and generate better-qualified leads.",
    goal: "Support B2B trust and improve conversion from service pages.",
    solution: "Built a clean corporate information architecture with conversion-ready CTA blocks and scalable responsive modules.",
    highlights: ["B2B trust-forward design", "Clear service blocks", "Fast responsive rendering", "Professional brand consistency"],
    thumbnails: t("provider-steel"),
    industryNotes: "Corporate sites win with clarity, reliability signals, and frictionless contact.",
  },
  {
    slug: "jdigital-xi",
    title: "JDigital XI",
    url: "https://jdigital-xi.vercel.app/",
    category: "Agency / Corporate",
    tags: commonTags,
    featured: false,
    year: 2026,
    description: "Agency website tailored for international client presentation and stronger consultation-driven conversion.",
    goal: "Position services professionally and increase inbound project consultations.",
    solution: "Designed a polished agency interface with strong visual hierarchy and conversion-ready service storytelling.",
    highlights: ["Agency-grade layout system", "Consultation CTA flow", "Mobile-first execution", "SEO-optimized structure"],
    thumbnails: t("jdigital-xi"),
    industryNotes: "Agency buyers evaluate clarity, quality cues, and trust signal consistency.",
  },
  {
    slug: "jdigital-solutions",
    title: "JDigital Solutions",
    url: "https://jdigitalsolutions.vercel.app/",
    category: "Agency / Corporate",
    tags: commonTags,
    featured: true,
    year: 2026,
    description: "Premium agency website engineered to build service trust and convert qualified traffic into consultations.",
    goal: "Convert service traffic into qualified project conversations.",
    solution:
      "Implemented a premium agency presentation with strategic conversion flow, optimized mobile behavior, and performance-conscious UI.",
    highlights: ["Conversion-led agency UX", "Strong value proposition blocks", "Responsive quality", "SEO and speed ready"],
    thumbnails: t("jdigital-solutions"),
    industryNotes: "B2B agency growth is driven by clarity, trust, and frictionless inquiry pathways.",
  },
];

export const featuredProjects = projects.filter((project) => project.featured);
export const liveProjects = projects;
export const featuredLiveProjects = featuredProjects;

export function getProjectBySlug(slug: string) {
  return projects.find((project) => project.slug === slug);
}

export function getProjectThumbnail(project: Project, device: "desktop" | "tablet" | "mobile") {
  if (device === "desktop") return project.thumbnails.desktop;
  if (device === "tablet") return project.thumbnails.tablet ?? project.thumbnails.desktop;
  return project.thumbnails.mobile ?? project.thumbnails.tablet ?? project.thumbnails.desktop;
}

export function getProjectStageImage(project: Project) {
  return `/thumbnails/${project.slug}.jpg`;
}

export const projectStats = {
  liveWebsites: 23,
  industries: 12,
};
